### ISSUE TITLE
clean house

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/hazelnut-dynamics-agda#49]
- [x] update the readme
- [x] check over comments, add docs where needed
- [x] push lemmas into the right files, maybe rename some
- [x] package up some how, maybe Docker process that @cyrus- found?

**Comment by ivoysey** [comment]
https://mpickering.github.io/posts/2018-09-19-nix-artefacts.html

**Comment by ivoysey** [comment]
comment somewhere in the readme about the trickiness around weakening

**Comment by cyrus-** [comment]
since we have extra room in the paper, maybe put some of the stuff about weakening and sigma representation in the Agda section itself
